### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by ac-daman** [Axiologue/ShoeScraper#8]
Sorry, newbie here. After i download the file, is there anything I have to edit in the code, or do I just run it and if so, how? thx

**Comment by MattBroach** [comment]
Hey @ac-daman, this web scraper is built on top of an open-source web scraping project called Scrapy.  If you haven't used it before, I'd recommend checking out the [scrapy tutorial](https://doc.scrapy.org/en/latest/intro/tutorial.html) -- after you've gone through that, I think you'll have a much better understanding of how to run the Shoe Scraper.

I haven't updated the scraping tools in over a year at this point, so I also imagine at this point many of the websites won't be scraped properly.  But feel free to give it a try, once you've gone through the Scrapy tutorial.

**Comment by ac-daman** [comment]
Great, thank you!
